// Generated by scripts/sync-env.js — commit this for community pull users
// Maintainer pushes cache here; other users pull without configuring a URL.
var DEFAULT_SHEET_URL = "https://docs.google.com/spreadsheets/d/1qwQ3w-3gpf8JKsIjc4f3L10D9pIKl0b-zAxZD2jVmaE";
