const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const secretsPath = path.join(root, 'config', 'secrets.js');
const defaultsPath = path.join(root, 'config', 'defaults.js');

if (!fs.existsSync(envPath)) {
  console.error('Missing .env file at', envPath);
  process.exit(1);
}

const envText = fs.readFileSync(envPath, 'utf8');
let apiKey = '';
let taostatsApiKey = '';
let sheetUrl = '';

for (const line of envText.split(/\r?\n/)) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) {
    continue;
  }

  const apiMatch = trimmed.match(/^(?:API_KEY|TAO_API_KEY)\s*=\s*(.+)$/);
  if (apiMatch) {
    apiKey = apiMatch[1].trim().replace(/^['"]|['"]$/g, '');
    continue;
  }

  const taostatsMatch = trimmed.match(/^TAOSTATS_API_KEY\s*=\s*(.+)$/);
  if (taostatsMatch) {
    taostatsApiKey = taostatsMatch[1].trim().replace(/^['"]|['"]$/g, '');
    continue;
  }

  const sheetMatch = trimmed.match(/^SHEET_URL\s*=\s*(.+)$/);
  if (sheetMatch) {
    sheetUrl = sheetMatch[1].trim().replace(/^['"]|['"]$/g, '');
  }
}

if (!apiKey && !taostatsApiKey && !sheetUrl) {
  console.error('No API_KEY, TAO_API_KEY, TAOSTATS_API_KEY, or SHEET_URL found in .env');
  process.exit(1);
}

fs.mkdirSync(path.dirname(secretsPath), { recursive: true });

if (apiKey || taostatsApiKey) {
  const secretsContents = `// Generated by scripts/sync-env.js — do not commit
var TAO_API_KEY = ${JSON.stringify(apiKey)};
var TAOSTATS_API_KEY = ${JSON.stringify(taostatsApiKey)};
`;
  fs.writeFileSync(secretsPath, secretsContents, 'utf8');
  console.log('Wrote', secretsPath);
}

if (sheetUrl) {
  const defaultsContents = `// Generated by scripts/sync-env.js — commit this for community pull users
// Maintainer pushes cache here; other users pull without configuring a URL.
var DEFAULT_SHEET_URL = ${JSON.stringify(sheetUrl)};
`;
  fs.writeFileSync(defaultsPath, defaultsContents, 'utf8');
  console.log('Wrote', defaultsPath);
}
